name: firewatcher

services:
  bot:
    image: ghcr.io/dy0gu/firewatcher:latest
    build:
      context: .
    pull_policy: always
    restart: unless-stopped
    init: true
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f bot.py"]
      interval: 10s
      timeout: 5s
      retries: 5
