# https://github.com/googleapis/release-please?tab=readme-ov-file#how-do-i-change-the-version-number
name: "release"

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tag-name: ${{ steps.metadata.outputs.tag_name }}
      release-created: ${{ steps.metadata.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: metadata
        with:
          config-file: release.json
          manifest-file: .manifest.json
  build:
    permissions:
      contents: read
      packages: write
    needs: [metadata]
    if: ${{ needs.metadata.outputs.release-created}}
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.metadata.outputs.tag-name }}
    secrets: inherit
